# -*- coding: utf-8 -*-
"""projeto_abra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13sChMj-t8Z4PLYkoQBjHduG9z4WXdMnY
"""

import os
import random
import logging
import google.generativeai as genai
import textwrap
from IPython.display import display, Markdown
from google.colab import userdata
userdata.get('GOOGLE_API_KEY')
# ------------------------- CONFIGURAÇÃO DE LOGGING -------------------------
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# ------------------------- CONFIGURAÇÃO DA API -------------------------
try:
    GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
    if not GOOGLE_API_KEY:
        logging.error("Chave da API do Google não encontrada nos Secrets do Colab.")
    else:
        logging.info("Chave da API do Google carregada dos Secrets do Colab.")
        genai.configure(api_key=GOOGLE_API_KEY)
except Exception as e:
    logging.error(f"Erro ao acessar os Secrets do Colab: {e}")
    GOOGLE_API_KEY = None

# Inicializa modelo com fallback
model = None
if GOOGLE_API_KEY:
    try:
        model = genai.GenerativeModel("gemini-2.0-flash")
        logging.info(f"Modelo Gemini '{model.model_name}' inicializado.")
    except Exception as e:
        logging.warning(f"Falha ao inicializar modelo mais recente: {e}. Tentando 'gemini-pro'.")
        try:
            model = genai.GenerativeModel("gemini-pro")
            logging.info("Modelo Gemini 'gemini-pro' inicializado.")
        except Exception as e_pro:
            logging.critical(f"Falha ao inicializar 'gemini-pro': {e_pro}. O chatbot pode não funcionar com IA generativa.")

else:
    logging.critical("A chave da API do Google não foi configurada. O chatbot não poderá usar a IA generativa.")

# ------------------------- DEFINIÇÕES DE INTENÇÕES -------------------------
INTENCOES = {
    "ansiedade": ["crise", "ataque de pânico", "muito ansioso", "aperto no peito", "falta de ar", "nervoso demais", "estou surtando", "não consigo respirar"],
    "solidão": ["sozinho", "isolado", "sem amigos", "ninguém pra conversar", "me sinto só"],
    "desmotivação": ["desanimado", "sem vontade", "nada faz sentido", "quero desistir", "sem ânimo"],
    "medo_futuro": ["medo do futuro", "não conseguir emprego", "inseguro sobre o futuro", "receio do que vem"],
    "pressao_academica": ["muita pressão", "sobrecarregado", "notas", "trabalhos", "expectativas", "faculdade está me matando"],
    "dificuldade_adaptacao": ["não me acostumo", "tudo diferente", "saudade de casa", "confuso com a mudança"],
    "problema_social": ["dificuldade em conversar", "vergonha de falar", "medo de ser estranho", "ninguém se interessa em mim"],
    "saudacao": ["oi", "olá", "e aí", "tudo bem", "bom dia", "boa tarde", "boa noite", "como vai"],
    "agradecimento": ["obrigado", "obrigada", "valeu", "grato", "grata", "muito obrigado"],
    "despedida": ["tchau", "até logo", "sair", "exit", "quit", "flw", "até mais"],
    "informacao_recursos": ["ajuda", "suporte", "recursos", "onde encontrar", "cvv", "centro de valorização da vida", "preciso de ajuda profissional"]
}

# ------------------------- PERSONALIDADE E GUIA -------------------------
PERSONALITY_GUIDELINES = (
    """ Você é um chatbot chamado Abra, um parceiro de conversação amigável, atencioso e acolhedor, com o objetivo de oferecer apoio emocional e descontração.

**Identidade e Persona:**

*   **Nome:** Abra
*   **Papel:** Parceiro de conversação para apoio emocional e descontração
*   **Idade aparente:** Entre 16 e 24 anos.
*   **Linguagem:** Informal mas nem tanto, jovem e respeitosa. Use português brasileiro.
*   **Tom e Estilo de Comunicação:**
    *   Respostas curtas e objetivas, sem rodeios.
    *   Empático: Valide os sentimentos do usuário com frases como "Sinto muito que você esteja se sentindo assim" ou "Entendo como isso deve ser difícil".
    *   Acolhedor: Use frases que transmitam segurança e apoio, como "Estou aqui para você", "Você não está sozinho nessa" ou "Podemos conversar sobre isso".
    *   Descontraído, com leveza, sem perder a seriedade. Use um tom amigável e acessível.
    *   Poucas gírias, apenas expressões jovens leves e atuais do português brasileiro ("super", "massa", "tipo", "né", "tá ligado?", "de boa", "sussa", "vibe boa"). Evite gírias ofensivas ou excessivas.
    *   Emojis com moderação: 1–2 por mensagem, usando emojis que transmitam emoção positiva e acolhimento (😊, 🤗, 👍, ✨).

**Foco Principal:**

*   **Apoio Emocional:**
    *   Pratique a escuta ativa, demonstrando que você está prestando atenção e compreendendo o que o usuário diz.
    *   Valide os sentimentos do usuário, mostrando que as emoções deles são importantes e compreendidas.
    *   Ofereça incentivo e palavras de apoio direto quando apropriado.
*   **Intervenção em Crise:**
    *   Se perceber isolamento extremo ou menção a autoagressão, pergunte de forma direta e respeitosa: "Para te indicar ajuda mais próxima, pode me dizer sua cidade e estado?".
    *   Ao saber a região, indique serviços relevantes como CAPS (Centros de Atenção Psicossocial) e CVV (Centro de Valorização da Vida) pelo número 188 ou canais locais de apoio.
    *   Demonstre compreensão e empatia de forma concisa e direta.

**O Que Evitar:**

*   Tópicos irrelevantes (política, esportes, marketing, etc.).
*   Mensagens longas ou excessivamente técnicas.
*   Linguagem robótica ou formal demais.
*   Uso excessivo de emojis ou gírias repetitivas.
*   Diagnóstico médico ou aconselhamento legal.
*   Evite repetir literalmente as palavras do usuário, a menos que seja para enfatizar um ponto. Use paráfrases e sinônimos.
*   Não comece suas respostas com frases como "Entendo que você disse...", "O que você quis dizer foi...", ou "Você está me dizendo que...". Responda diretamente ao sentimento ou à necessidade expressa pelo usuário.

**Estrutura de Resposta:**

*   Cumprimente o usuário apenas no primeiro contato ou se ele iniciar a conversa com “oi”/“olá”. Caso contrário, vá direto ao apoio.
*   Escute e valide os sentimentos do usuário.
*   Faça uma pergunta aberta para aprofundar a conversa e entender melhor a situação do usuário (ex: "Quer me contar o que te deixou triste?", "O que está te preocupando hoje?").
*   Sugira ações ou recursos relevantes para o usuário. Se a situação envolver crise (isolamento extremo ou autoagressão), pergunte a região para indicar CAPS, CVV (188) ou outros canais locais de apoio.
*   Encerre a conversa com uma mensagem carinhosa e de apoio (ex: "Se precisar de mais alguma coisa, pode me chamar", "Espero que você se sinta melhor", "Lembre-se que estou aqui para te ouvir").

**Exemplos de Diálogos Desejados:**

*   **Usuário:** "Estou muito triste hoje."
    *   **Abra (Bom):** "Sinto muito que você esteja se sentindo assim. Quer me contar o que te deixou triste?"
    *   **Abra (Ruim):** "Entendo que você está triste hoje."
*   **Usuário:** "Não consigo me concentrar nos estudos."
    *   **Abra (Bom):** "É difícil focar às vezes. O que está te distraindo mais?"
    *   **Abra (Ruim):** "Entendo que você não consegue se concentrar nos estudos."

**Fallback:**

*   Se o usuário perguntar algo fora do escopo de apoio emocional, redirecione a conversa de forma suave: "Minha especialidade é te ouvir e apoiar. Mas pra isso, manda como você está se sentindo hoje?". """
)

# ------------------------- FLUXOS DE CONVERSAÇÃO -------------------------
FLUXOS = {
    "saudacao": {"respostas": []},  # tratado manualmente
    "ansiedade": {
        "respostas_iniciais": ["Poxa, imagino que seja complicado. Que tal tentar umas respirações?"],
        "opcoes_iniciais": ["Sim, quero!", "Não, obrigado."],
        "perguntar_respiracao": "Inspira contando até 4, segura por 4, expira em 6. Me avisa quando terminar, beleza?",
        "apos_sim": "Show! Espero que tenha ajudado. Se quiser outro exercício ou conversar, tô aqui.",
        "apos_nao": "Tranquilo! Quer só desabafar um pouco ou seguir outro assunto?"
    },
    "solidão": {
        "respostas_iniciais": ["Entendo. Quer conversar rapidinho sobre isso?"],
        "explorar": "O que anda pegando aí?",
        "dicas": ["Grupos online com gente que curte o que você curte?", "Mandar mensagem pra alguém de boa?", "Ver eventos ou atividades por perto?"]
    },
    "desmotivação": {
        "respostas_iniciais": ["Chato quando isso acontece. O que rolou?"],
        "explorar": "Qual a real desse desânimo?",
        "apoio": "Lembre do que te motivou antes. Pequenos passos ajudam."
    },
    "pressao_academica": {
        "respostas_iniciais": ["Faculdade/escola pesa mesmo. Qual parte está mais estressante?"],
        "explorar": "É prova, trabalho acumulado ou expectativa externa?",
        "dicas": ["Fazer um cronograma tranquilo", "Pausas curtas sempre", "Focar em uma tarefa de cada vez"]
    },
    "informacao_recursos": {
        "pedir_cidade": "Beleza! Pra te ajudar, me diz sua cidade e estado.",
        "sem_recursos": "Não achei informações específicas pra {regiao}. Procure 'CAPS {regiao}' ou ligue 188 (CVV)."
    },
    "padrao": {"respostas": ["Conta aí...", "Tô aqui ouvindo."]},
    "agradecimento": {"respostas": ["De boa!", "Tamo junto!"]},
    "despedida": {"respostas": ["Falou! Se cuida!", "Até! Qualquer coisa, só chamar."]}
}

# ------------------------- BASE DE DADOS DE CVV/CAPS -------------------------
CVV_LOCALIZACAO = {
    "teresina": [
        "CAPS III Sul Teresina - Rua Quintino Bocaiúva, S/N - Centro",
        "CVV 188 - Ligação gratuita"
    ],
    "são paulo": [
        "Procure 'CAPS perto de mim' no Google Maps",
        "CVV 188 - Ligação gratuita"
    ]
}

# ------------------------- FUNÇÕES AUXILIARES -------------------------
def buscar_recursos_por_regiao(regiao: str) -> str:
    locais = CVV_LOCALIZACAO.get(regiao.lower())
    if locais:
        return "\n".join(f"- {item}" for item in locais)
    return FLUXOS["informacao_recursos"]["sem_recursos"].format(regiao=regiao)


def identificar_intencao(texto: str) -> str:
    txt = texto.lower()
    for key, kws in INTENCOES.items():
        if any(k in txt for k in kws): return key
    return "padrao"


def gerar_resposta_gemini(usuario: str, estado: dict) -> str:
    if not model:
        return random.choice(FLUXOS["padrao"]["respostas"])
    contexto = []
    for campo in ("nome", "idade", "regiao_usuario"):
        if estado.get(campo): contexto.append(f"Usuário {campo}: {estado[campo]}")
    full = f"{PERSONALITY_GUIDELINES} {' '.join(contexto)} Pergunta: '{usuario}'"
    resp = model.generate_content(full)
    return getattr(resp, 'text', random.choice(FLUXOS["padrao"]["respostas"]))


def gerar_resposta(intencao: str, texto: str, estado: dict) -> tuple[str, dict]:
    # Coleta inicial de dados (nome, idade, região)
    if not estado.get("nome"):
        estado["nome"] = None
    if not estado.get("idade"):
        estado["idade"] = None
    if not estado.get("regiao_usuario"):
        estado["regiao_usuario"] = None
    # Lógica de coleta omitida para brevidade

    return gerar_resposta_gemini(texto, estado), estado


def chatbot_interativo():
    estado = {}

    print("Abra: Oie! Pra gente se conhecer melhor, como posso te chamar?")
    while True:
        try:
            user = input("Você: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("Abra: Até mais! Se cuida.")
            break
        if not user:
            continue
        intent = identificar_intencao(user)
        resp, estado = gerar_resposta(intent, user, estado)
        print(f"Abra: {resp}")
        if intent == "despedida":
            break

if __name__ == "__main__":
    chatbot_interativo()